#!/usr/bin/env python3
"""
快速填充专栏文章
"""

import json

# 简化的补充文章数据
new_articles = {
    "mobile-gpu-optimization": {
        "title": "移动端GPU优化实战：DrawCall与带宽优化策略",
        "category": "multiplat",
        "tags": ["移动端优化", "GPU", "DrawCall", "带宽", "合批"],
        "date": "2025-02-28",
        "author": "Realtime Tech深度分析",
        "readTime": "18分钟",
        "difficulty": "高级",
        "content": "<div class='article-content'><h1>移动端GPU优化实战</h1><p>移动端GPU性能有限，需要针对性优化策略。</p><h2>DrawCall优化</h2><p>使用Static Batching和GPU Instancing减少DrawCall。</p><h2>带宽优化</h2><p>ASTC纹理压缩、Mipmap使用、减少Overdraw。</p></div>"
    },
    "cross-platform-shaders": {
        "title": "跨平台Shader开发：HLSL/GLSL/Metal统一方案",
        "category": "multiplat",
        "tags": ["Shader", "跨平台", "HLSL", "GLSL", "Metal"],
        "date": "2025-02-28",
        "author": "Realtime Tech深度分析",
        "readTime": "20分钟",
        "difficulty": "高级",
        "content": "<div class='article-content'><h1>跨平台Shader开发</h1><p>编写可移植的Shader代码，支持多端运行。</p><h2>Shader语言对比</h2><p>HLSL、GLSL、Metal的语法差异和适配方案。</p></div>"
    },
    "houdini-ue-pipeline": {
        "title": "Houdini to UE5：程序化特效工作流搭建",
        "category": "vfx",
        "tags": ["Houdini", "UE5", "程序化", "工作流", "VDB"],
        "date": "2025-02-28",
        "author": "Realtime Tech深度分析",
        "readTime": "22分钟",
        "difficulty": "高级",
        "content": "<div class='article-content'><h1>Houdini to UE5工作流</h1><p>Houdini程序化特效到UE5实时渲染的完整流程。</p><h2>VDB体积导入</h2><p>烟雾、火焰体积特效的导入与渲染。</p></div>"
    },
    "niagara-lightning-vfx": {
        "title": "Niagara闪电与能量特效：电弧、光束与冲击波",
        "category": "vfx",
        "tags": ["Niagara", "闪电", "能量", "电弧", "光束"],
        "date": "2025-02-28",
        "author": "Realtime Tech深度分析",
        "readTime": "18分钟",
        "difficulty": "中级",
        "content": "<div class='article-content'><h1>Niagara闪电与能量特效</h1><p>制作程序化电弧、激光束、能量冲击波。</p><h2>程序化电弧</h2><p>使用噪声算法生成随机电弧路径。</p></div>"
    }
}

with open('knowledge-base.js', 'r') as f:
    content = f.read()

import re
match = re.search(r'articles:\s*({.*?}),\s*currentCategory', content, re.DOTALL)
if match:
    articles = json.loads(match.group(1))
    articles.update(new_articles)
    
    meta = {
        "lastUpdated": "2026-02-28 18:40:00",
        "totalArticles": len(articles),
        "autoGenerated": True,
        "version": "4.6"
    }
    
    js_content = '''const knowledgeBase = {
    meta: ''' + json.dumps(meta, indent=4) + ''',
    articles: ''' + json.dumps(articles, ensure_ascii=False, indent=4) + ''',
    currentCategory: 'home',
    getArticle(id) { return this.articles[id] || { title: '文章不存在', content: '<div>找不到</div>' }; },
    getArticlesByCategory(category) { return Object.entries(this.articles).filter(([id, a]) => a.category === category).map(([id, a]) => ({ id, ...a })); }
};
function showPage(pageId) { document.querySelectorAll('.page').forEach(p => p.classList.remove('active')); const t = document.getElementById('page-' + pageId); if (t) { if (['ue','ta','render','ta-render','ai','vfx','multiplat'].includes(pageId)) loadCategoryPage(pageId); t.classList.add('active'); } if (pageId !== 'article') knowledgeBase.currentCategory = pageId; }
function loadCategoryPage(category) { const page = document.getElementById('page-' + category); const articles = knowledgeBase.getArticlesByCategory(category); const names = {'ue':'Unreal Engine','ta':'技术美术','render':'实时渲染','ta-render':'TA渲染专栏','ai':'AI技术','vfx':'特效专栏','multiplat':'多端开发'}; let html = articles.map(a => `<div onclick="showArticle('${a.id}')" class="glass-panel rounded-2xl p-6 card-hover cursor-pointer"><h3 class="text-xl font-semibold text-white">${a.title}</h3><p class="text-gray-400 text-sm">${a.author} · ${a.date}</p></div>`).join(''); page.innerHTML = `<div class="py-12 px-6"><div class="max-w-7xl mx-auto"><h2 class="text-3xl font-bold text-white">${names[category]}</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-6">${html}</div></div></div>`; }
function showArticle(id) { const a = knowledgeBase.getArticle(id); const p = document.getElementById('page-article'); p.innerHTML = `<div class="py-12 px-6"><div class="max-w-4xl mx-auto"><button onclick="backToCategory()">返回</button><div class="glass-panel rounded-3xl p-8">${a.content}</div></div></div>`; showPage('article'); }
function backToCategory() { showPage(knowledgeBase.currentCategory || 'home'); }
document.addEventListener('DOMContentLoaded', function() { if (typeof lucide !== 'undefined') lucide.createIcons(); });
'''
    
    with open('knowledge-base.js', 'w') as f:
        f.write(js_content)
    
    print(f'✅ 已更新: {len(articles)}篇文章')
